In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
 arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr * arr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])