In [4]:
import numpy as np

In [5]:
python_array = [0, 1, 2]

In [6]:
np_array = np.array(python_array)

In [7]:
np_array

array([0, 1, 2])

In [8]:
python_array

[0, 1, 2]

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.linspace(0, 5, 20) # 20 evenly spaced points between 0 and 5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.15400744, 0.94417046, 0.60904463, 0.48607069, 0.91535637])

In [21]:
np.random.randn(5) # normal distribution around 0

array([-0.54389851, -0.01747647,  0.39154463,  1.01654524, -0.17249934])

In [25]:
random_arr = np.random.randint(1, 100, 9)

In [28]:
reshaped = random_arr.reshape(3, 3)

In [30]:
reshaped.shape

(3, 3)

In [31]:
reshaped.dtype

dtype('int64')