In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
a = arr[0:3]

In [6]:
a

array([0, 1, 2])

In [7]:
a[:] = 99

In [8]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
b = arr.copy()

In [10]:
b[:] = 100

In [11]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
b

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
matrix[0, 2]

3

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
bool_arr

NameError: name 'bool_arr' is not defined

In [6]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])